"""Alert Model - System Alert for Authority Review"""
from typing import Optional
from datetime import datetime
from sqlalchemy import String, DateTime, ForeignKey, JSON, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.database.base import Base
from app.models.base import TimestampMixin


class Alert(TimestampMixin, Base):
    """System alert requiring authority review.

    Alerts are automatically generated by the matching engine when
    high-confidence matches are found. Authorities can acknowledge,
    resolve, or dismiss alerts through the API.
    """
    __tablename__ = "alerts"

    incident_id: Mapped[str] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("rescue_sessions.id"),
        nullable=False,
    )
    matched_incident_id: Mapped[Optional[str]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("rescue_sessions.id"),
        nullable=True,
    )
    alert_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )
    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default="low",
    )
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default="open",
    )
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    description: Mapped[str] = mapped_column(
        String(1000),
        nullable=False,
    )
    source: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        server_default="system",
    )
    extra_data: Mapped[Optional[dict]] = mapped_column(
        JSON,
        nullable=True,
    )
    acknowledged_by: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
    )
    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    resolved_by: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
    )
    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Indexes
    __table_args__ = (
        Index("ix_alerts_incident_id", "incident_id"),
        Index("ix_alerts_status", "status"),
        Index("ix_alerts_severity", "severity"),
        Index("ix_alerts_created_at", "created_at"),
    )