"""Timeline API Endpoints - Rescue Incident Timeline"""
from fastapi import APIRouter, Depends, status
from sqlalchemy.ext.asyncio import AsyncSession
from app.database.connection import get_db
from app.services.timeline_service import TimelineService
from app.schemas.timeline_event import TimelineEventResponse

router = APIRouter(tags=["timeline"])


@router.get(
    "/rescue/incidents/{incident_id}/timeline",
    response_model=list[TimelineEventResponse],
    status_code=status.HTTP_200_OK,
    summary="Get incident timeline",
    description=(
        "Retrieves all timeline events for a rescue incident, "
        "ordered by timestamp ascending. Timeline events are "
        "auto-generated by the system during incident lifecycle."
    ),
)
async def get_incident_timeline(
    incident_id: str,
    session: AsyncSession = Depends(get_db),
) -> list[TimelineEventResponse]:
    """Get all timeline events for an incident."""
    service = TimelineService(session)
    return await service.get_incident_timeline(incident_id)